{% set version = "9.1.15" %}

package:
  name: swi-prolog
  version: {{ version }}

source:
# url: https://www.swi-prolog.org/download/devel/src/swipl-{{ version }}.tar.gz
# sha256: c8dc901bfe2a10990473b2f2b79d92332ebc23b8b6f79107177258b708a57595
  git_url: https://github.com/SWI-Prolog/swipl-devel.git
# git_rev: HEAD
# git_depth: 1

build:
  number: 18

requirements:
  build:
    - git
    - cmake
    - pkg-config	# [not win]
    - ninja		# [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - zlib
    - pthreads-win32	# [win]
    - gmp		# [not osx and not win]
    - gperftools	# [not win]
    - python
    - libedit		# [not win]
    - readline		# [not win]
    - openssl
    - unixodbc		# [not win]
    - libarchive
    - pcre2
    - yaml
    - ossuuid		# [not osx and not win]
    - libdb		# [not osx]
    - openjdk
    - fontconfig	# [not win]
    - xorg-libice	# [not win]
    - xorg-libsm	# [not win]
    - xorg-libx11	# [not win]
    - xorg-libxaw	# [not win]
    - xorg-libxext	# [not win]
    - xorg-libxinerama	# [not win]
    - xorg-libxmu	# [not win]
    - xorg-libxpm	# [not win]
    - xorg-libxrender	# [not win]
    - xorg-libxt	# [not win]
    - jpeg

  run:
    - zlib
    - pthreads-win32	# [win]
    - gmp		# [not osx and not win]
    - gperftools	# [not win]
    - python
    - libedit		# [not win]
    - readline		# [not win]
    - openssl
    - unixodbc		# [not win]
    - libarchive
    - pcre2
    - yaml
    - ossuuid		# [not osx and not win]
    - libdb		# [not osx]
    - openjdk
    - python		# [not win]
    - fontconfig	# [not win]
    - xorg-libice	# [not win]
    - xorg-libsm	# [not win]
    - xorg-libx11	# [not win]
    - xorg-libxaw	# [not win]
    - xorg-libxext	# [not win]
    - xorg-libxinerama	# [not win]
    - xorg-libxmu	# [not win]
    - xorg-libxpm	# [not win]
    - xorg-libxrender	# [not win]
    - xorg-libxt	# [not win]
    - jpeg

test:

about:
  home: https://www.swi-prolog.org
  license: BSD-2
  license_family: BSD
  summary: SWI-Prolog system
